# DOCKERFILE FOR GESTIVASEC FRONTEND SPA SERVING
FROM node:18-alpine as builder

WORKDIR /app

COPY frontend/package.json ./
RUN npm install || true

COPY frontend/ ./

FROM nginx:alpine as runner

COPY --from=builder /app /usr/share/nginx/html
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
