-- MIGRATION 003: CREATE ORGANIZATIONS TABLE AND INDEXES (SLICE-002)
CREATE TABLE IF NOT EXISTS organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE_ORGANIZATION',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_organizations_slug ON organizations(slug);

-- SEED DEFAULT ORGANIZATIONS
INSERT INTO organizations (id, name, slug, status)
VALUES 
    ('00000000-0000-0000-0000-000000000001', 'GestivaOne Corporation', 'gestivaone-corp', 'ACTIVE_ORGANIZATION'),
    ('00000000-0000-0000-0000-000000000002', 'Festa Event Systems', 'festa-events', 'ACTIVE_ORGANIZATION')
ON CONFLICT (slug) DO NOTHING;
